version: 2.1
orbs:
  firebase-app-distribution: nnsnodnb/firebase-app-distribution@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
  # Create a job to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  command-tests:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Put ipa file
          command: |
            echo "${IPA_BASE64}" | base64 -d > sample.ipa
      - run:
          name: Setup app-distribution-key.json
          command: |
            echo "${GOOGLE_SERVICE_ACCOUNT_JSON}" > /tmp/app-distribution-key.json
      - firebase-app-distribution/deploy:
          app: ${FIREBASE_APP}
          binary_path: sample.ipa
          service_credentials_file: /tmp/app-distribution-key.json
          groups: default
          release_note: $(git log -n 10 --pretty=format:"%h %s")
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - command-tests:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: nnsnodnb/firebase-app-distribution
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
